/* eslint-disable @cspell/spellchecker */
import { getCounter, initCounter, setupRule } from './rules.ts'

export function setupRules(counter: number) {
	initCounter(counter)
	setupRule('issued', 'article:published_time')
	setupRule('issued', 'article:published_time')
	setupRule('author', 'article:author')
	setupRule('issued', 'citation_year')
	setupRule('issued', 'citation_publication_date')
	setupRule('title', 'citation_title')
	setupRule('author', 'citation_author')
	setupRule('author', 'twitter:data1')
	setupRule('author', 'twitter:creator')
	setupRule('author', 'author')
	setupRule('author', 'authors')
	setupRule('language', 'dc:language')
	setupRule('publisher', 'dc:publisher')
	setupRule('author', 'dc:creator')
	setupRule('description', 'dc:description')
	setupRule('issued', 'dc:date')
	setupRule('issued', 'dc.date.created')
	setupRule('issued', 'dcterms.issued')
	setupRule('modified', 'dcterms.modified')
	setupRule('modified', 'dc.date.modified')
	setupRule('title', 'og:title')
	setupRule('URL', 'og:url')
	setupRule('subtype', 'og:type')
	setupRule('author', 'og:author')
	setupRule('title', 'og:title')
	setupRule('title', 'citation_title')
	setupRule('firstPage', 'og:first_page')
	setupRule('firstPage', 'citation_first_page')
	setupRule('lastPage', 'og:last_page')
	setupRule('lastPage', 'citation_last_page')
	setupRule('doi', 'og:doi')
	setupRule('doi', 'citation_doi')
	setupRule('source', 'og:journal_title')
	setupRule('source', 'citation_journal_title')
	setupRule('journalAbbrev', 'og:journal_abbrev')
	setupRule('journalAbbrev', 'citation_journal_abbrev')
	setupRule('description', 'og:description')
	return getCounter()
}
